PostgreSQL:
  restart: always
  image: sameersbn/postgresql:10-1
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=admin
    - DB_PASS=admin
    - DB_NAME=
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
